SocialNetwork/SocialNetwork.Web/Controllers/PostController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;
using SocialNetwork.Models;
using SocialNetwork.Models.Common.Enums;
using SocialNetwork.Services.DTOs;
using SocialNetwork.Services.Services.Contracts;
using SocialNetwork.Web.Hubs;
using SocialNetwork.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SocialNetwork.Web.Controllers
{
    [Authorize]
    public class PostController : Controller
    {
        private readonly IUserService userService;
        private readonly IPostService postService;
        private readonly ICommentService commentService;
        private readonly ILikeService likeService;
        private readonly UserManager<User> userManager;
        private readonly IMapper mapper;
        private readonly IHubContext<ChatHub> hubContext;

        public PostController(IUserService userService,
            IPostService postService,
            ICommentService commentService,
            ILikeService likeService,
            UserManager<User> userManager,
            IMapper mapper,
            IHubContext<ChatHub> hubContext)
        {
            this.userService = userService;
            this.postService = postService;
            this.commentService = commentService;
            this.likeService = likeService;
            this.userManager = userManager;
            this.mapper = mapper;
            this.hubContext = hubContext;
        }

        public async Task<ActionResult> NewsFeed()
        {
            var user = await this.userManager.GetUserAsync(User);

            var feed = await this.postService.GetUserFriendsPostsAsync(user.Id);

            var posts = new List<PostCommentViewModel>();

            foreach (var item in feed)
            {
                var posViewModel = this.mapper.Map<PostViewModel>(item);
                var postCommentModel = new PostCommentViewModel()
                {
                    Post = posViewModel,
                    NewComment = new CommentViewModel()
                };
                posts.Add(postCommentModel);
            }

            var result = posts.Where(x => x.Post.Visibility != Visibility.OnlyMe)
                              .OrderByDescending(x => x.Post.CreatedOn)
                              .ToList();
            return View(result);
        }

        [HttpGet]
        public ActionResult Search()
        {
            return View(new SearchViewModel());
        }

        [HttpPost]
        public async Task<IActionResult> Search(SearchViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return this.BadRequest();
            }
            try
            {
                if (model.SearchCriteria.ToLower() == "users")
                {
                    List<UserDTO> users = new List<UserDTO>();

                    if (model.SearchWord == null)
                    {
                        var allUsers = await this.userService.GetAllAsync();
                        users = allUsers.OrderBy(u => u.DisplayName).ToList();
                    }
                    else
                    {
                        var foundUsers = await this.userService.GetByUserNameAsync(model.SearchWord, model.SortOrder);
                        users = foundUsers.ToList();
                    }

                    var searchModel = new SearchViewModel
                    {
                        Users = users
                               .Select(this.mapper.Map<UserSearchViewModel>)
                               .ToList()
                    };

                    return View(searchModel);
                }
                else if (model.SearchCriteria.ToLower() == "posts")
                {
                    var result = await this.postService.GetByContentAsync(model.SearchWord, model.SortOrder);

                    //  if (!result.Any())
                    //  {
                    //      return this.NotFound();
                    //  }

                    var searchModel = new SearchViewModel
                    {
                        Posts = result
                               .Select(this.mapper.Map<PostViewModel>)
                               .ToList()
                    };

                    return View(searchModel);
                }
            }
            catch
            {
                return RedirectToAction("Search");
            }
            //Remove this.
            return Ok();
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(PostViewModel postViewModel)
        {
            try
            {
                var user = await this.userManager.GetUserAsync(User);

                var postDTO = this.mapper.Map<PostDTO>(postViewModel);
                postDTO.UserId = user.Id;

                var result = await this.postService.CreateAsync(postDTO, postViewModel.file);

                return RedirectToAction("Profile", "Account");
            }
            catch (Exception)
            {
                return this.BadRequest();
            }
        }

        [HttpGet]
        public IActionResult ChangeProfilePhoto()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> ChangeProfilePhoto(PostViewModel postViewModel)
        {
            try
            {
                var user = await this.userManager.GetUserAsync(User);

                var result = await this.postService.ChangeDisplayPicture(postViewModel.file, user.Id, "profile");

                return RedirectToAction("Profile", "Account");
            }
            catch (Exception)
            {
                return this.BadRequest();
            }
        }

        [HttpPost]
        public async Task<IActionResult> ChangeCoverPhoto(PostViewModel postViewModel)
        {
            try
            {
                var user = await this.userManager.GetUserAsync(User);

                var result = await this.postService.ChangeDisplayPicture(postViewModel.file, user.Id, "cover");

                return RedirectToAction("Profile", "Account");
            }
            catch (Exception)
            {
                return this.BadRequest();
            }
        }

        [HttpPost]
        public async Task<IActionResult> Comment(PostCommentViewModel viewModel)
        {
            try
            {
                var user = await this.userManager.GetUserAsync(User);

                var comment = this.mapper.Map<CommentDTO>(viewModel.NewComment);
                comment.UserId = user.Id;

                await this.commentService.CreateAsync(comment); // TODO: Do we need to get the new comment?

                return this.Redirect("NewsFeed");
            }
            catch
            {
                return RedirectToAction("Error", "Home");
            }
        }

        [HttpPost]
        public async Task<IActionResult> Like(int postId, bool isLiked)
        {
            try
            {
                var user = await this.userManager.GetUserAsync(User);
                var postDTO = await this.postService.GetPostByIdAsync(postId);
                postDTO.UserId = user.Id;

                var likes = postDTO.Likes.Count;

                var likeDislike = isLiked
                    ? await this.likeService.DislikeAsync(postDTO)
                    : await this.likeService.LikeAsync(postDTO);

                likes = isLiked ? likes - 1 : likes + 1;

                await this.hubContext.Clients.All.SendAsync("Test", postDTO.Id, likes);
                return this.Ok();
            }
            catch
            {
                return RedirectToAction("Error", "Home");
            }
        }
    }
}

SocialNetwork/SocialNetwork.Web/Views/Shared/_CreatePostPartial.cshtml
@model PostViewModel

<!-- Write a comment -->
<div class="social-timelines p-relative">
    <div class="row timeline-right p-t-35">
        <div class="col-2 col-sm-2 col-xl-1"></div>
        <div class="col-10 col-sm-10 col-xl-11 p-l-5 p-b-35">
            <div class="card">
                <div class="card-header">
                    <h5 class="card-header-text">Update status</h5>
                </div>
                <div class="card-block user-box">
                    <form class="" method="post" enctype="multipart/form-data" asp-controller="Post" asp-action="Create">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group">
                            <textarea rows="5" cols="5" class="form-control" placeholder="What's on your mind?" asp-for="Content"></textarea>
                            <span asp-validation-for="Content" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Visibility" class="control-label"></label>
                            <select asp-for="Visibility" asp-items="@(new SelectList((IEnumerable<Visibility>)ViewData["visibility"]))" class="form-control"></select>
                        </div>
                        <div class="form-group">
                            <label> Upload photo </label>
                            <label asp-for="file" class="control-label"></label>
                            <input asp-for="file" class="form-control" />
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Create" class="btn btn-primary btn-block" />
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SocialNetwork/SocialNetwork.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no" />
    <title>@ViewData["Title"] - SocialNetwork.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>

<body>
    <!-- Navbar -->
    <partial name="_Navbar" />

    <!-- Newsbar -->
    @*@await Component.InvokeAsync("Newsbar")*@

    <div class="">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/js/particles.js"></script>
    <script src="~/lib/microsoft/signalr/dist/browser/signalr.js"></script>
    <script src="~/js/chat.js"></script>
    <script src="~/js/signalrReqHandler.js"></script>
    <script src="~/js/site.js"></script>
    <script src="~/js/alime.bundle.js"></script>
    <script src="~/js/active.js"></script>
    <script src="~/js/paginate.js"></script>

    @RenderSection("Scripts", required: false)

</body>
</html>

SocialNetwork/SocialNetwork.Web/Views/Shared/_Navbar.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager
<!-- Chat -->
@if (SignInManager.IsSignedIn(User))
{
    @await Component.InvokeAsync("Chat")
}

<!-- Header Area Start -->
<header class="header-area">
    <!-- Main Header Start -->
    <div class="main-header-area">
        <div class="classy-nav-container breakpoint-off">
            <div class="container">
                <!-- Classy Menu -->
                <nav class="classy-navbar justify-content-between" id="alimeNav">

                    <!-- Logo -->
                    <a class="nav-brand" asp-controller="Home" asp-action="Index" style="color: white">@*<img src="~/img/logo2.png" style="width: 100px;">*@Connectiverse</a>

                    <!-- Navbar Toggler -->
                    <div class="classy-navbar-toggler">
                        <span class="navbarToggler"><span></span><span></span><span></span></span>
                    </div>

                    <!-- Menu -->
                    <div class="classy-menu">

                        <!-- Nav Start -->
                        <div class="classynav">
                            <ul id="nav">
                                @if (SignInManager.IsSignedIn(User))
                                {
                                    <li>
                                        <a class="nav-link" asp-controller="Post" asp-action="Search" title="Search">
                                            <svg width="1em" height="1em" viewBox="0 0 15 15" class="bi bi-search" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                                <path fill-rule="evenodd" d="M10.442 10.442a1 1 0 0 1 1.415 0l3.85 3.85a1 1 0 0 1-1.414 1.415l-3.85-3.85a1 1 0 0 1 0-1.415z" />
                                                <path fill-rule="evenodd" d="M6.5 12a5.5 5.5 0 1 0 0-11 5.5 5.5 0 0 0 0 11zM13 6.5a6.5 6.5 0 1 1-13 0 6.5 6.5 0 0 1 13 0z" />
                                            </svg>
                                        </a>
                                    </li>
                                    <li>
                                        <a asp-controller="Post" asp-action="NewsFeed" title="Newsfeed">
                                            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-newspaper" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                                <path fill-rule="evenodd" d="M0 2.5A1.5 1.5 0 0 1 1.5 1h11A1.5 1.5 0 0 1 14 2.5v10.528c0 .3-.05.654-.238.972h.738a.5.5 0 0 0 .5-.5v-9a.5.5 0 0 1 1 0v9a1.5 1.5 0 0 1-1.5 1.5H1.497A1.497 1.497 0 0 1 0 13.5v-11zM12 14c.37 0 .654-.211.853-.441.092-.106.147-.279.147-.531V2.5a.5.5 0 0 0-.5-.5h-11a.5.5 0 0 0-.5.5v11c0 .278.223.5.497.5H12z" />
                                                <path d="M2 3h10v2H2V3zm0 3h4v3H2V6zm0 4h4v1H2v-1zm0 2h4v1H2v-1zm5-6h2v1H7V6zm3 0h2v1h-2V6zM7 8h2v1H7V8zm3 0h2v1h-2V8zm-3 2h2v1H7v-1zm3 0h2v1h-2v-1zm-3 2h2v1H7v-1zm3 0h2v1h-2v-1z" />
                                            </svg>
                                        </a>
                                    </li>
                                    <li>
                                        <a asp-controller="Account" asp-action="FriendRequests" title="Friend Requests">
                                            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-people-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                                <path fill-rule="evenodd" d="M7 14s-1 0-1-1 1-4 5-4 5 3 5 4-1 1-1 1H7zm4-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm-5.784 6A2.238 2.238 0 0 1 5 13c0-1.355.68-2.75 1.936-3.72A6.325 6.325 0 0 0 5 9c-4 0-5 3-5 4s1 1 1 1h4.216zM4.5 8a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5z" />
                                            </svg>
                                        </a>
                                    </li>
                                    @*                                  For future extension
                                        <li>
                                            <a asp-controller="Chat" asp-action="Messenger">
                                                <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-chat-dots-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                                    <path fill-rule="evenodd" d="M16 8c0 3.866-3.582 7-8 7a9.06 9.06 0 0 1-2.347-.306c-.584.296-1.925.864-4.181 1.234-.2.032-.352-.176-.273-.362.354-.836.674-1.95.77-2.966C.744 11.37 0 9.76 0 8c0-3.866 3.582-7 8-7s8 3.134 8 7zM5 8a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm4 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm3 1a1 1 0 1 0 0-2 1 1 0 0 0 0 2z" />
                                                </svg>
                                            </a>
                                        </li>*@
                                    <li>
                                        <a>
                                            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-person-circle" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                                <path d="M13.468 12.37C12.758 11.226 11.195 10 8 10s-4.757 1.225-5.468 2.37A6.987 6.987 0 0 0 8 15a6.987 6.987 0 0 0 5.468-2.63z" />
                                                <path fill-rule="evenodd" d="M8 9a3 3 0 1 0 0-6 3 3 0 0 0 0 6z" />
                                                <path fill-rule="evenodd" d="M8 1a7 7 0 1 0 0 14A7 7 0 0 0 8 1zM0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8z" />
                                            </svg>
                                            <svg width="1em" height="1em" viewBox="0 -3 20 20" class="bi bi-caret-down-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                                <path d="M7.247 11.14L2.451 5.658C1.885 5.013 2.345 4 3.204 4h9.592a1 1 0 0 1 .753 1.659l-4.796 5.48a1 1 0 0 1-1.506 0z" />
                                            </svg>
                                        </a>
                                        <ul class="dropdown">
                                            <li>
                                                <a asp-controller="Account" asp-action="Profile">
                                                    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-file-person" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                                        <path fill-rule="evenodd" d="M12 1H4a1 1 0 0 0-1 1v10.755S4 11 8 11s5 1.755 5 1.755V2a1 1 0 0 0-1-1zM4 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H4z" />
                                                        <path fill-rule="evenodd" d="M8 10a3 3 0 1 0 0-6 3 3 0 0 0 0 6z" />
                                                    </svg> Profile
                                                </a>
                                            </li>
                                            @if (User.IsInRole("Admin"))
                                            {
                                                <li>
                                                    <a asp-controller="Admin" asp-action="ListUsers">
                                                        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-grid-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                                            <path fill-rule="evenodd" d="M1 2.5A1.5 1.5 0 0 1 2.5 1h3A1.5 1.5 0 0 1 7 2.5v3A1.5 1.5 0 0 1 5.5 7h-3A1.5 1.5 0 0 1 1 5.5v-3zm8 0A1.5 1.5 0 0 1 10.5 1h3A1.5 1.5 0 0 1 15 2.5v3A1.5 1.5 0 0 1 13.5 7h-3A1.5 1.5 0 0 1 9 5.5v-3zm-8 8A1.5 1.5 0 0 1 2.5 9h3A1.5 1.5 0 0 1 7 10.5v3A1.5 1.5 0 0 1 5.5 15h-3A1.5 1.5 0 0 1 1 13.5v-3zm8 0A1.5 1.5 0 0 1 10.5 9h3a1.5 1.5 0 0 1 1.5 1.5v3a1.5 1.5 0 0 1-1.5 1.5h-3A1.5 1.5 0 0 1 9 13.5v-3z" />
                                                        </svg> Admin Panel
                                                    </a>
                                                </li>
                                            }
                                            <li>
                                                <a asp-area="Identity" asp-page="/Account/Manage/Index">
                                                    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-tools" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                                        <path fill-rule="evenodd" d="M0 1l1-1 3.081 2.2a1 1 0 0 1 .419.815v.07a1 1 0 0 0 .293.708L10.5 9.5l.914-.305a1 1 0 0 1 1.023.242l3.356 3.356a1 1 0 0 1 0 1.414l-1.586 1.586a1 1 0 0 1-1.414 0l-3.356-3.356a1 1 0 0 1-.242-1.023L9.5 10.5 3.793 4.793a1 1 0 0 0-.707-.293h-.071a1 1 0 0 1-.814-.419L0 1zm11.354 9.646a.5.5 0 0 0-.708.708l3 3a.5.5 0 0 0 .708-.708l-3-3z" />
                                                        <path fill-rule="evenodd" d="M15.898 2.223a3.003 3.003 0 0 1-3.679 3.674L5.878 12.15a3 3 0 1 1-2.027-2.027l6.252-6.341A3 3 0 0 1 13.778.1l-2.142 2.142L12 4l1.757.364 2.141-2.141zm-13.37 9.019L3.001 11l.471.242.529.026.287.445.445.287.026.529L5 13l-.242.471-.026.529-.445.287-.287.445-.529.026L3 15l-.471-.242L2 14.732l-.287-.445L1.268 14l-.026-.529L1 13l.242-.471.026-.529.445-.287.287-.445.529-.026z" />
                                                    </svg> Settings
                                                </a>
                                            </li>
                                            <li>
                                                <form asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                                                    <button type="submit" style="background: transparent; border: none">
                                                        <a>
                                                            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-power" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                                                <path fill-rule="evenodd" d="M5.578 4.437a5 5 0 1 0 4.922.044l.5-.866a6 6 0 1 1-5.908-.053l.486.875z" />
                                                                <path fill-rule="evenodd" d="M7.5 8V1h1v7h-1z" />
                                                            </svg> Logout
                                                        </a>
                                                    </button>
                                                </form>
                                            </li>
                                        </ul>
                                    </li>
                                }
                                else
                                {
                                    <li><a asp-area="Identity" asp-page="/Account/Register">Register</a></li>
                                    <li><a asp-area="Identity" asp-page="/Account/Login">Login</a></li>
                                }
                            </ul>
                            <!-- Search Icon -->
                            <div class="search-icon" data-toggle="modal" data-target="#searchModal"><i class="ti-search"></i></div>
                        </div>
                        <!-- Nav End -->
                    </div>
                </nav>
            </div>
        </div>
    </div>
</header>
<!-- Header Area End -->

SocialNetwork/SocialNetwork.Web/Views/Shared/_PostViewPartial.cshtml
@model PostCommentViewModel
@inject UserManager<User> UserManager
@{
    var user = await UserManager.GetUserAsync(User);
    Model.isLiked = Model.Post.Likes.Any(l => l.UserId == user.Id);

    int commentCounter = 0;
}

<div class="social-timelines p-relative">
    <div class="row timeline-right p-t-35">
        <div class="col-2 col-sm-2 col-xl-1">
            <div class="social-timelines-left">
                <a asp-controller="Account" asp-action="FriendProfile" asp-route-userId="@Model.Post.UserId">
                    <img class="img-radius timeline-icon" src="@Model.Post.UserProfilePictureUrl" alt="">
                </a>
            </div>
        </div>
        <div class="col-10 col-sm-10 col-xl-11 p-l-5 p-b-35">
            <div class="card">
                @if (!string.IsNullOrEmpty(Model.Post.PhotoUrl))
                {
                    <div class="picture-frame-black">
                        <img src="@Model.Post.PhotoUrl" class="img-fluid width-100 picture-in-frame">
                    </div>
                }
                <div class="card-block">
                    <div class="timeline-details">
                        <p class="text-muted">@Model.Post.Content</p>
                    </div>
                </div>
                <div class="card-block b-b-theme b-t-theme social-msg">

                    <i class="fa fa-thumbs-up" onclick="likepost(@Model.Post.Id, this)" isliked="@(Model.isLiked ? "true" : "false")"
                       style="@(Model.isLiked ? "blue" : "powderblue")font-size:24px;color:@(Model.isLiked ? "blue" : "powderblue"); cursor:pointer;"></i>

                    <span id="likesCount_@Model.Post.Id" class="b-r-muted" likesCount="@Model.Post.Likes.Count">Likes (@Model.Post.Likes.Count)</span>
                    <a onclick="showComments(@Model.Post.Id)" style="cursor: pointer;"> <i class="icofont icofont-comment text-muted"></i> <span class="b-r-muted">Comments (@Model.Post.Comments.Count)</span></a>
                </div>
                <div class="card-block user-box" id="comments_@Model.Post.Id" data-display="on">
                    
                    @foreach (var comment in Model.Post.Comments)
                    {
                        <div class="media m-b-20" @(commentCounter < 3 ? "" : "hidden")>
                            <a class="media-left" href="#">
                                <img class="media-object img-radius m-r-20" src="@comment.UserProfilePictureUrl" width="10" height="10">
                            </a>
                            <div class="media-body b-b-muted social-client-description">
                                <div class="chat-header">@comment.UserDisplayName<span class="text-muted">@comment.CreatedOn</span></div>
                                <p class="text-muted">@comment.Content</p>
                            </div>
                        </div>

                        commentCounter++;
                    }

                    <!-- Comment on a post -->
                    <div class="media">
                        <a class="media-left" href="#">
                            <img class="media-object img-radius m-r-20" src="@user.ProfilePictureUrl">
                        </a>
                        <div class="media-body">
                            <form class="" method="post" asp-controller="Post" asp-action="Comment">
                                <div class="">
                                    <input rows="5" cols="5" class="form-control" asp-for="NewComment.Content" placeholder="Write Something here..."></input>
                                    <input style="display: none" asp-for="NewComment.PostId" value="@Model.Post.Id" />
                                    <div class="form-group">
                                        <input type="submit" value="Create" class="btn btn-primary btn-block" />
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@*<script>
    function submitComment(button) {

        console.log(button);

        let commentContent = $(button).siblings('.content').val();
        console.log(commentContent);

        let postId = $(button).siblings('.postId').val();

        let vm = {
            viewModel: {
                Post: {
                    Id: postId
                },
                NewComment: {
                    Content: commentContent
                },
                Test: "Ali"
            }
        };

        debugger;
        $.ajax({
            type: "POST",
            url: "/Post/Comment",
            data: JSON.stringify(vm),
            dataType: "json",
            contentType: "application/json",
        });
    }
</script>

@section Scripts{
    <script>
        $('#addComment').click(function () {
            var json = @Model.NewComment.Content;
            console.log(json);
            $.ajax({
                        type: "POST",
                        url: "https://localhost:5001/Post/Comment",
                        data: JSON.stringify(json),
                        contentType: "application/json; charset=utf-8",
                        processData: 'json',
                success: function (data) {
                    console.log(data);
                    $().html(data)
                        }
                    })
                })
    </script>
}*@

SocialNetwork/SocialNetwork.Web/Views/Shared/_ProfileTabsPartial.cshtml
@model UserViewModel
@inject UserManager<User> UserManager
@{
    var user = await this.UserManager.GetUserAsync(User);
    var isLoggedIn = user.Id == Model.Id ? true : false;

    var postViewModel = new PostViewModel
    {
        UserId = Model.Id
    };

    var filteredPosts = Model.Posts.Where(p => p.PhotoUrl != null).ToList();
}

<div class="col-xl-9 col-lg-8 col-md-8 col-xs-12 ">

    <!-- Profile Tabs -->
    <div class="card social-tabs">
        <ul class="nav nav-tabs md-tabs tab-timeline" role="tablist">
            <li class="nav-item">
                <a class="nav-link active" data-toggle="tab" href="#timeline" role="tab">Timeline</a>
                <div class="slide"></div>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#about" role="tab">About</a>
                <div class="slide"></div>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#photos" role="tab">Photos</a>
                <div class="slide"></div>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#friends" role="tab">Friends</a>
                <div class="slide"></div>
            </li>
        </ul>
    </div>

    <!-- Profile Tabs Content -->
    <div class="tab-content">

        <!-- TIMELINE tab -->

        <div class="tab-pane active" id="timeline">
            <!-- Create a post -->
            @if (isLoggedIn)
            {
                <partial name="_CreatePostPartial" model="postViewModel" />
            }

            <!-- All posts -->
            <div class="row">
                <div class="col-md-12 timeline-dot">
                    @foreach (var post in Model.Posts)
                    {
                        if (post.UserId == default)
                        {
                            continue;
                        }
                        var postCommentVM = new PostCommentViewModel { Post = post };
                        <partial name="_PostViewPartial" model="postCommentVM" />
                    }
                </div>
            </div>
        </div>

        <!-- ABOUT tab -->
        <partial name="_ProfileInfoTabPartial" model="Model" />

        <!-- PHOTOS tab -->
        <partial name="_ProfileGalleryTabPartial" model="filteredPosts" />  @*Only Posts with images*@

        <!-- FRIENDS tab -->
        <div class="tab-pane" id="friends">
            <div class="row">
                @foreach (var friend in Model.Friends)
                {
                    <partial name="_ProfileFriendsTabPartial" model="friend" />
                }
            </div>
        </div>

    </div>

</div>